// Generated by CoffeeScript 1.6.3
this.App.module('Sidepanel', function(Sidepanel, App, Backbone, Marionette, $, _) {
  'use strict';
  Sidepanel.Layout = Marionette.Layout.extend({
    template: '#sidepanel',
    regions: {
      menuBefore: '#menu-before',
      playlists: '#playlists',
      menuAfter: '#menu-after',
      trackinfo: '#trackinfo-region'
    },
    events: {
      'submit #search-form': 'searchSubmit',
      'mousedown #sidepanel-handle': 'handleMouseDown'
    },
    searchSubmit: function(e) {
      var query;
      e.preventDefault();
      query = this.$el.find('#searchbar').val().trim();
      if (query.length > 0) {
        document.location.href = "#/tracks/search?q=" + encodeURIComponent(query);
        return App.execute("search:tracks", query);
      }
    },
    initialize: function() {
      this.holdingHandle = false;
      this.mouseDownX = 0;
      $(window).mousemove(this.onMouseMove.bind(this));
      $(window).mouseup(this.onMouseUp.bind(this));
      return $(window).blur(this.onMouseUp.bind(this));
    },
    onClose: function() {},
    handleMouseDown: function(e) {
      this.holdingHandle = true;
      return this.handleX = this.leftPane.width() - e.pageX;
    },
    onMouseMove: function(e) {
      var w;
      if (!this.holdingHandle) {
        return;
      }
      w = Math.max(Math.min(e.pageX + this.handleX, 480), 128) + "px";
      this.leftPane.css({
        width: w
      });
      return $(".trackinfo #coverart").css({
        'max-height': w
      });
    },
    onMouseUp: function(e) {
      if (!this.holdingHandle) {
        return;
      }
      return this.holdingHandle = false;
    },
    onRender: function() {
      return this.leftPane = $(".left-pane");
    }
  });
  Sidepanel.MenuItem = Marionette.ItemView.extend({
    getTemplate: function() {
      if (this.model.get('className') !== 'separator') {
        return '#sidepanel-menuitem';
      } else {
        return '#empty-template';
      }
    },
    tagName: 'li',
    className: function() {
      return this.model.get('className');
    },
    modelEvents: {
      'change': 'render'
    },
    events: {
      'click span': 'clicked'
    },
    clicked: function() {
      return this.trigger('menuitem:clicked', this.model);
    }
  });
  Sidepanel.Menu = Marionette.CollectionView.extend({
    tagName: 'ul',
    itemView: Sidepanel.MenuItem
  });
  return Sidepanel.Trackinfo = Marionette.ItemView.extend({
    template: '#trackinfo-template',
    className: 'trackinfo-wrapper',
    modelEvents: {
      'change': 'render'
    },
    onRender: function() {
      var urlMedium, urlPlaceholder, urlThumb;
      urlPlaceholder = "img/album-placeholder.png";
      if (!this.model.get('download')) {
        return;
      }
      if (this.model.get('download').art) {
        urlMedium = this.model.get('download').art + "/medium";
        urlThumb = this.model.get('download').art + "/thumb";
      } else {
        urlMedium = urlThumb = urlPlaceholder;
      }
      $("#coverart").prop('src', urlPlaceholder);
      $("#coverart").prop('src', urlMedium);
      return $("#coverart-thumb").css({
        'background-image': "url('" + urlThumb + "')"
      });
    }
  });
});
