// Generated by CoffeeScript 1.6.3
this.config = {
  host: "https://eqbeats.org"
};

this.App = (function(Backbone, Marionette) {
  'use strict';
  var App;
  Backbone.emulateHTTP = true;
  App = new Marionette.Application;
  App.addRegions({
    sideRegion: "#side-region",
    mainRegion: "#main-region",
    playerRegion: "#player-region"
  });
  App.reqres.setHandler("default:region", function() {
    return App.mainRegion;
  });
  App.on('initialize:before', function(options) {
    return this.execute('current:user:set', options.currentUserId);
  });
  App.addInitializer(function() {
    this.module('Sidepanel').start({
      region: this.sideRegion
    });
    return this.module('Player').start({
      region: this.playerRegion
    });
  });
  App.commands.setHandler("register:instance", function(instance, id) {
    return App.register(instance, id);
  });
  App.commands.setHandler("unregister:instance", function(instance, id) {
    return App.unregister(instance, id);
  });
  App.on("initialize:after", function(options) {
    return this.startHistory();
  });
  return App;
})(Backbone, Marionette);
