// Generated by CoffeeScript 1.6.3
this.App.module('History', function(History, App, Backbone, Marionette, $, _) {
  'use strict';
  var API;
  History.Router = Marionette.AppRouter.extend({
    appRoutes: {
      "history": "showHistory"
    }
  });
  API = {
    showHistory: function() {
      return new History.Show.Controller;
    }
  };
  return App.addInitializer(function() {
    return new History.Router({
      controller: API
    });
  });
});
