// Generated by CoffeeScript 1.6.3
this.App.module('History.Show', function(Show, App, Backbone, Marionette, $, _) {
  'use strict';
  return Show.Controller = App.Controllers.Base.extend({
    initialize: function(options) {
      var history,
        _this = this;
      history = App.request("history:entities");
      this.layout = this.getLayoutView();
      this.listenTo(this.layout, 'show', function() {
        return _this.historyRegion(history);
      });
      return this.show(this.layout);
    },
    historyRegion: function(history) {
      var listView;
      listView = this.getHistoryView(history);
      return this.layout.history.show(listView);
    },
    getHistoryView: function(history) {
      return new App.View.Playlist({
        collection: history
      });
    },
    getLayoutView: function() {
      return new Show.Layout;
    }
  });
});
