// Generated by CoffeeScript 1.6.3
this.App.module('Iframe.Show', function(Show, App, Backbone, Marionette, $, _) {
  'use strict';
  return Show.Controller = App.Controllers.Base.extend({
    initialize: function(options) {
      var model, url;
      url = options.url;
      model = new Backbone.Model({
        url: url
      });
      this.iframeView = this.getIframeView(model);
      return this.show(this.iframeView);
    },
    getIframeView: function(model) {
      return new Show.IframeView({
        model: model
      });
    },
    getLayoutView: function() {
      return new Show.Layout;
    }
  });
});
