// Generated by CoffeeScript 1.6.3
this.App.module('Iframe', function(Iframe, App, Backbone, Marionette, $, _) {
  'use strict';
  var API, urls;
  Iframe.Router = Marionette.AppRouter.extend({
    appRoutes: {
      ":webpage": "showIframe",
      "web/track/:id": "showTrackPage",
      "web/user/:id": "showUserPage"
    }
  });
  API = {
    showIframe: function(webpage) {
      if (urls[webpage]) {
        return this.showUrl(urls[webpage]);
      }
    },
    showUrl: function(url) {
      return new Iframe.Show.Controller({
        url: url
      });
    },
    showTrackPage: function(id) {
      return this.showUrl("https://eqbeats.org/track/" + id);
    },
    showUserPage: function(id) {
      return this.showUrl("https://eqbeats.org/user/" + id);
    }
  };
  urls = {
    blog: 'http://blog.eqbeats.org/'
  };
  return App.addInitializer(function() {
    return new Iframe.Router({
      controller: API
    });
  });
});
