// Generated by CoffeeScript 1.6.3
this.App.module('Index', function(Index, App, Backbone, Marionette, $, _) {
  'use strict';
  var API;
  Index.Router = Marionette.AppRouter.extend({
    appRoutes: {
      "": "showIndex"
    }
  });
  API = {
    showIndex: function() {
      return new Index.Show.Controller;
    }
  };
  return App.addInitializer(function() {
    return new Index.Router({
      controller: API
    });
  });
});
