// Generated by CoffeeScript 1.6.3
this.App.module('Index.Show', function(Show, App, Backbone, Marionette, $, _) {
  'use strict';
  return Show.Controller = App.Controllers.Base.extend({
    initialize: function(options) {
      var featured, latest,
        _this = this;
      featured = App.request("featured:entities");
      latest = App.request("latest:entities");
      this.layout = this.getLayoutView();
      this.listenTo(this.layout, 'show', function() {
        _this.featuredRegion(featured);
        return _this.latestRegion(latest);
      });
      return this.show(this.layout);
    },
    featuredRegion: function(featured) {
      var listView;
      listView = this.getFeaturedView(featured);
      return this.show(listView, {
        loading: {
          entities: featured
        },
        region: this.layout.featured
      });
    },
    latestRegion: function(latest) {
      var listView;
      listView = this.getLatestView(latest);
      return this.show(listView, {
        loading: {
          entities: latest
        },
        region: this.layout.latest
      });
    },
    getFeaturedView: function(featured) {
      return new App.View.TracklistBig({
        collection: featured
      });
    },
    getLatestView: function(latest) {
      return new App.View.TracklistBig({
        collection: latest
      });
    },
    getLayoutView: function() {
      return new Show.Layout;
    }
  });
});
