// Generated by CoffeeScript 1.6.3
this.App.module('Lists.Show', function(Show, App, Backbone, Marionette, $, _) {
  'use strict';
  return Show.Controller = App.Controllers.Base.extend({
    initialize: function(options) {
      var list, model, name, title,
        _this = this;
      title = options.title, name = options.name;
      list = App.request(name + ":entities");
      model = new Backbone.Model({
        title: title,
        name: name
      });
      this.layout = this.getLayoutView(model);
      this.listenTo(this.layout, 'show', function() {
        var listView;
        return listView = _this.listRegion(list);
      });
      this.listenTo(this.layout, 'reload:list', function() {
        return list.fetch();
      });
      return this.show(this.layout);
    },
    listRegion: function(list) {
      var listView;
      listView = this.getListView(list);
      this.show(listView, {
        loading: {
          entities: list
        },
        region: this.layout.list
      });
      return listView;
    },
    getListView: function(list) {
      return new App.View.Playlist({
        collection: list
      });
    },
    getLayoutView: function(model) {
      return new Show.Layout({
        model: model
      });
    }
  });
});
