// Generated by CoffeeScript 1.6.3
this.App.module('Lists', function(Lists, App, Backbone, Marionette, $, _) {
  'use strict';
  var API;
  Lists.Router = Marionette.AppRouter.extend({
    appRoutes: {
      "featured": "showFeatured",
      "latest": "showLatest",
      "random": "showRandom"
    }
  });
  API = {
    showFeatured: function() {
      return new Lists.Show.Controller({
        title: "Featured",
        name: "featured"
      });
    },
    showLatest: function() {
      return new Lists.Show.Controller({
        title: "Latest",
        name: "latest"
      });
    },
    showRandom: function() {
      return new Lists.Show.Controller({
        title: "Random",
        name: "random"
      });
    }
  };
  return App.addInitializer(function() {
    return new Lists.Router({
      controller: API
    });
  });
});
