// Generated by CoffeeScript 1.6.3
this.App.module('Queue.Show', function(Show, App, Backbone, Marionette, $, _) {
  'use strict';
  return Show.Controller = App.Controllers.Base.extend({
    initialize: function(options) {
      var queue,
        _this = this;
      queue = App.request("queue:entities");
      this.layout = this.getLayoutView();
      this.listenTo(this.layout, 'show', function() {
        return _this.queueRegion(queue);
      });
      return this.show(this.layout);
    },
    queueRegion: function(queue) {
      var listView;
      listView = this.getQueueView(queue);
      return this.layout.queue.show(listView);
    },
    getQueueView: function(queue) {
      return new Show.List({
        collection: queue
      });
    },
    getLayoutView: function() {
      return new Show.Layout;
    }
  });
});
