// Generated by CoffeeScript 1.6.3
this.App.module('Queue', function(Queue, App, Backbone, Marionette, $, _) {
  'use strict';
  var API;
  Queue.Router = Marionette.AppRouter.extend({
    appRoutes: {
      "queue": "showQueue"
    }
  });
  API = {
    showQueue: function() {
      return new Queue.Show.Controller;
    }
  };
  return App.addInitializer(function() {
    return new Queue.Router({
      controller: API
    });
  });
});
