// Generated by CoffeeScript 1.6.3
this.App.module('Search', function(Search, App, Backbone, Marionette, $, _) {
  'use strict';
  var API;
  Search.Router = Marionette.AppRouter.extend({
    appRoutes: {
      "tracks/search?q=:query": "showSearchResult"
    }
  });
  API = {
    showSearchResult: function(query) {
      return new Search.Result.Controller({
        query: query
      });
    }
  };
  return App.addInitializer(function() {
    new Search.Router({
      controller: API
    });
    return App.commands.setHandler('search:tracks', API.showSearchResult);
  });
});
