// Generated by CoffeeScript 1.6.3
this.App.module('Search', function(Search, App, Backbone, Marionette, $, _) {
  'use strict';
  var API;
  Search.Router = Marionette.AppRouter.extend({
    appRoutes: {
      "search/": "showQueue"
    }
  });
  API = {
    showQueue: function() {
      return new Search.Show.Controller;
    }
  };
  return App.addInitializer(function() {
    return new Search.Router({
      controller: API
    });
  });
});
