// Generated by CoffeeScript 1.6.3
this.App.module('Track', function(Track, App, Backbone, Marionette, $, _) {
  'use strict';
  var API;
  Track.Router = Marionette.AppRouter.extend({
    appRoutes: {
      "track/:id": "showTrack"
    }
  });
  API = {
    showTrack: function(id) {
      return new Track.Show.Controller({
        id: id
      });
    }
  };
  return App.addInitializer(function() {
    return new Track.Router({
      controller: API
    });
  });
});
