// Generated by CoffeeScript 1.6.3
this.App.module('Track.Show', function(Show, App, Backbone, Marionette, $, _) {
  'use strict';
  return Show.Controller = App.Controllers.Base.extend({
    initialize: function(options) {
      var collection, id, track,
        _this = this;
      id = options.id;
      track = App.request("track:entity", id);
      collection = new Backbone.Collection([track]);
      collection.add(track);
      this.layout = this.getLayoutView(track);
      this.listenTo(this.layout, 'show', function() {
        var infoView;
        infoView = _this.showTrackInfoView(track);
        return _this.showTrackPlayerView(track);
      });
      return this.show(this.layout, {
        loading: {
          entities: track
        }
      });
    },
    showTrackInfoView: function(track) {
      var infoView;
      infoView = this.getInfoView(track);
      return this.layout.info.show(infoView);
    },
    showTrackPlayerView: function(track) {
      var playerView;
      playerView = this.getPlayerView(track);
      return this.layout.player.show(playerView);
    },
    getInfoView: function(track) {
      return new Show.Info({
        model: track
      });
    },
    getPlayerView: function(track) {
      return new Show.Player({
        model: track
      });
    },
    getLayoutView: function(track) {
      return new Show.Layout({
        model: track
      });
    }
  });
});
