// Generated by CoffeeScript 1.6.3
this.App.module('User', function(User, App, Backbone, Marionette, $, _) {
  'use strict';
  var API;
  User.Router = Marionette.AppRouter.extend({
    appRoutes: {
      "user/:id": "showUser",
      "user/:id/favourites": "showFavourites"
    }
  });
  API = {
    showUser: function(id) {
      return new User.Show.Controller({
        id: id
      });
    },
    showFavourites: function(id) {
      return new User.Favourites.Controller({
        id: id
      });
    }
  };
  return App.addInitializer(function() {
    return new User.Router({
      controller: API
    });
  });
});
