// Generated by CoffeeScript 1.6.3
this.App.module('Player', function(Player, App, Backbone, Marionette, $, _) {
  'use strict';
  Player.Layout = Marionette.Layout.extend({
    template: '#player-template',
    className: 'playercontrols',
    regions: {
      controls: '#media-controls',
      time: '#timeElapsed',
      duration: '#timeTotal',
      progress: '#progress-song'
    }
  });
  Player.Controls = Marionette.ItemView.extend({
    template: '#player-controls',
    events: {
      'click #next-track-btn': function() {
        return App.commands.execute("track:play:next");
      },
      'click #prev-track-btn': function() {
        return App.commands.execute("track:play:prev");
      },
      'click #play-pause-track-btn': function() {
        return App.commands.execute("track:toggle:play");
      }
    },
    onRender: function() {
      this.prevBtn = this.$el.find("#prev-track-btn");
      this.playBtn = this.$el.find("#play-pause-track-btn");
      return this.nextBtn = this.$el.find("#next-track-btn");
    },
    modelEvents: {
      'change:isPlaying': 'setPlayState',
      'change:canPlayPause': 'setCanPlayPause',
      'change:canNext': 'setCanNext',
      'change:canPrev': 'setCanPrev'
    },
    setPlayState: function() {
      if (this.model.get('isPlaying')) {
        return this.playBtn.addClass('paused');
      } else {
        return this.playBtn.removeClass('paused');
      }
    },
    setCanPlayPause: function() {
      return this.playBtn.prop('disabled', !this.model.get('canPlayPause'));
    },
    setCanNext: function() {
      return this.nextBtn.prop('disabled', !this.model.get('canNext'));
    },
    setCanPrev: function() {
      return this.prevBtn.prop('disabled', !this.model.get('canPrev'));
    }
  });
  Player.Time = Marionette.ItemView.extend({
    tagName: 'span',
    templateHelpers: {
      formatTime: function(time) {
        return App.request("format:time", time);
      }
    }
  });
  return Player.Progress = Marionette.ItemView.extend({
    template: '#player-progress',
    className: 'progressbar-track',
    modelEvents: {
      'change:time': 'updateProgress',
      'change:duration': 'updateProgress',
      'change:buffered': 'updateBuffered'
    },
    onRender: function() {
      this.progress = this.$el.find(".progressbar-progress");
      return this.buffered = this.$el.find(".progressbar-loaded");
    },
    updateProgress: function() {
      return this.progress.css({
        width: (this.model.get('time') / this.model.get('duration')) * 100 + "%"
      });
    },
    updateBuffered: function() {
      return this.buffered.css({
        width: (this.model.get('buffered') / this.model.get('duration')) * 100 + "%"
      });
    }
  });
});
